name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Run Generator tests
        run: node --test tests/data/*.test.js tests/generator/*.test.js
